icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
separator = "┊"
separator_bg = "#191222"
separator_fg = "#f6ee9d"
idle_bg = "#191222"
idle_fg = "#f6ee9d"
info_bg = "#191222"
info_fg = "#f6ee9d"
good_bg = "#191222"
good_fg = "#f6ee9d"
warning_bg = "#191222"
warning_fg = "#FCA26A"
critical_bg = "#D2236D"
critical_fg = "#f6ee9d"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "backlight"
device = "intel_backlight"
step_width = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
clickable = false

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "sound"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %r"
