[icons]
icons = "awesome5"

[theme]
theme = "plain"

[theme.overrides]
separator = "║"
separator_bg = "#d1dee9"
separator_fg = "#080404"
idle_bg = "#d1dee9"
idle_fg = "#080404"
info_bg = "#d1dee9"
info_fg = "#080404"
good_bg = "#d1dee9"
good_fg = "#080404"
warning_bg = "#d1dee9"
warning_fg = "#709FC2"
critical_bg = "#709FC2"
critical_fg = "#d1dee9"

[[block]]
block = "temperature"
interval = 10
format = " $icon $average ║ $min <-> $max"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
format = "$icon $ip $speed_up/s $speed_down/s"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
