icons = "awesome"

[theme]
name = "plain"

[theme.overrides]
separator = "║"
separator_bg = "{background}"
separator_fg = "{foreground}"
idle_bg = "{background}"
idle_fg = "{foreground}"
info_bg = "{background}"
info_fg = "{foreground}"
good_bg = "{background}"
good_fg = "{foreground}"
warning_bg = "{background}"
warning_fg = "{color2}"
critical_bg = "{color2}"
critical_fg = "{background}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{{min}}  {{max}}  {{average}}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format_mem = "{{mem_used}}({{mem_used_percents}})"
format_swap = "{{swap_used}}/{{swap_total}}({{swap_used_percents}})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "wlp82s0"
format = "{{ssid}} {{signal_strength}} {{ip}} {{speed_up;K*b}} {{speed_down;K*b}}"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %r"
