#!/usr/bin/env bash
# restart i3 so the bar colors update
i3-msg restart

# update discord colors
wal-discord


notify-send "Theme Changed"
exit 1

# if chrome isn't open, don't do anything
CHROMEWIN=$(xdotool search --name "Google Chrome" | head -n 1)
[ -z "$CHROMEWIN" ] && exit 1

# focus chrome
sleep 1
xdotool windowactivate $CHROMEWIN

# open the extensions window
xdotool key ctrl+t
xdotool key ctrl+l
xdotool type "chrome://extensions"
xdotool key Return

# click "load unpacked extension"
sleep 1
xdotool key Tab
xdotool key Tab

xdotool key Return
# navigate to the correct path
xdotool key ctrl+l
sleep 0.4
xdotool type "~/.config/chrome-theme"

# click 'ok'
xdotool key alt+o
sleep 1

# close the tab
xdotool windowactivate $CHROMEWIN
xdotool key ctrl+w
